[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"

[env]
PORT = "8000"
MONGODB_URL = "mongodb+srv://singhrishabh1670:020502@beyou.4anrb.mongodb.net/?retryWrites=true&w=majority&ssl=true&authSource=admin"
DB_NAME = "beyou_db"
RAILWAY_ENVIRONMENT = "production"